language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test   # gcc 5
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x # cmake 3.2
  - sudo apt-get -qq update
  # - sudo apt-get install -y libyajl-dev
  - sudo apt-get install -y wget cmake protobuf-compiler libprotobuf-dev zlib1g-dev libbz2-dev libsnappy-dev libjemalloc-dev

  # travis-ci is based on Ubuntu 14.04 LTS Trusty which ships 2.0.1 with an outdated api.
  # Compiling libyajl is fast, so do that.
  - git clone https://github.com/lloyd/yajl.git && cd yajl && mkdir build && cd build && cmake .. && make -j6 && sudo make install

  - sudo apt-get install -y gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 20
  #- git clone https://github.com/facebook/rocksdb.git && cd rocksdb && make shared_lib -j5 && sudo make install
  - wget http://factorcode.org/erg/librocksdb_3.1-1_amd64.deb
  - wget http://factorcode.org/erg/librocksdb-dev_3.1-1_amd64.deb
  - sudo dpkg -i ./librocksdb_3.1-1_amd64.deb
  - sudo dpkg -i ./librocksdb-dev_3.1-1_amd64.deb

before_script:
  - git clone https://github.com/pipedown/noise.git && cd noise && mkdir build && cd build && cmake ..

script: make -j6 && make test
