language: cpp

before_install:
  #- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -y wget cmake protobuf-compiler libyajl-dev zlib1g-dev libbz2-dev libsnappy-dev libjemalloc-dev
  #- sudo apt-get install -y gcc-5 g++-5
  #- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 20
  #- sudo apt-get install -y cmake protobuf-compiler libyajl-dev  zlib1g-dev libbz2-dev libsnappy-dev
  #- git clone https://github.com/facebook/rocksdb.git && cd rocksdb && make shared_lib -j5 && sudo make install
  - wget http://factorcode.org/erg/librocksdb_3.1-1_amd64.deb
  - sudo dpkg -i ./librocksdb_3.1-1_amd64.deb

before_script:
  - git clone git@github.com:pipedown/noise.git && cd noise && mkdir build && cd build && cmake ..

script: make -j6 && make test
